import type {LecturePresentation} from './types';

/** One semantic scene, with all related information visible together. */
export function renderLectureContent(host:HTMLElement,p:LecturePresentation,onFigure?:(index:number)=>void){
  const doc=host.ownerDocument;
  const make=(tag:string,className:string,text?:string)=>{const el=doc.createElement(tag);el.className=className;if(text)el.textContent=text;return el;};
  const article=make('article','native-lecture');article.dataset.layout=p.layout;
  const characters=p.groups.reduce((sum,g)=>sum+(g.title?.length||0)+g.items.join(' ').length,0);
  article.dataset.density=characters>(p.layout==='split'?900:1700)?'dense':characters>(p.layout==='split'?450:900)?'medium':'normal';
  article.dataset.figures=String(p.figures.length);article.dataset.groups=String(p.groups.length);
  const header=make('header','native-heading');if(p.eyebrow)header.append(make('p','native-eyebrow',p.eyebrow));header.append(make('h2','native-title',p.title));article.append(header);
  const body=make('div','native-body'),groups=make('div','native-groups');
  for(const group of p.groups){const section=make('section','native-group');if(group.title)section.append(make('h3','native-group-title',group.title));const list=make('ul','native-points');for(const text of group.items)list.append(make('li','',text));section.append(list);groups.append(section);}
  if(p.groups.length)body.append(groups);
  if(p.figures.length){const figures=make('div','native-figures');for(const [index,f]of p.figures.entries()){const figure=make('figure','native-figure'),image=doc.createElement('img');image.src=f.image;image.alt=f.alt;image.draggable=false;image.decoding='async';if(onFigure){const button=doc.createElement('button');button.type='button';button.className='native-image';button.setAttribute('aria-label',`${f.inspection?'Inspect chart':'Enlarge figure'}: ${f.alt}`);button.append(image);const hint=make('span','native-enlarge',f.inspection?'Inspect chart ↗':'↗');hint.setAttribute('aria-hidden','true');button.append(hint);button.addEventListener('click',()=>onFigure(index));figure.append(button);}else figure.append(image);if(f.caption)figure.append(make('figcaption','',f.caption));figures.append(figure);}body.append(figures);}
  article.append(body);if(p.takeaway)article.append(make('p','native-takeaway',p.takeaway));host.replaceChildren(article);fitLectureContent(host);doc.defaultView?.requestAnimationFrame(()=>fitLectureContent(host));
}

/** Fit long source text without hiding individual points or crowding the title. */
export function fitLectureContent(host:HTMLElement){
  const win=host.ownerDocument.defaultView;if(!win||win.innerWidth<=720)return;const article=host.querySelector<HTMLElement>('.native-lecture');if(!article)return;
  article.style.removeProperty('--native-size');
  const body=article.querySelector<HTMLElement>('.native-body'),groups=article.querySelector<HTMLElement>('.native-groups'),point=article.querySelector<HTMLElement>('.native-points li');
  if(!body||!groups||!point||article.dataset.layout==='gallery')return;
  let size=parseFloat(win.getComputedStyle(point).fontSize),minimum=Math.max(18,Math.min(25,win.innerWidth*.014));
  for(let attempt=0;attempt<6&&groups.scrollHeight>body.clientHeight+1&&size>minimum;attempt++){size=Math.max(minimum,size*Math.min(.93,body.clientHeight/groups.scrollHeight));article.style.setProperty('--native-size',`${size}px`);}
}

// Shared by the audience canvas and the separate same-origin presenter window.
export const nativeLectureCSS=`
.native-lecture{--native-size:clamp(21px,2.08vw,34px);box-sizing:border-box;display:flex;flex-direction:column;gap:22px;width:100%;height:100%;min-width:0;min-height:0;color:#e9f1ed;font-family:system-ui,sans-serif;text-align:left}
.native-lecture *{box-sizing:border-box}.native-heading{flex:none;display:block;padding:0;background:none;margin:0}.native-eyebrow{color:#86bdaa;text-transform:uppercase;font-size:12px;letter-spacing:.18em;margin:0 0 9px;font-weight:600}.native-title{font-size:clamp(30px,3.15vw,56px);line-height:1.08;letter-spacing:-.035em;font-weight:550;margin:0;color:#f1f7f4;max-width:32ch}
.native-body{flex:1;min-height:0;display:grid;grid-template-columns:minmax(0,1fr);gap:36px;align-items:safe center}.native-groups{min-width:0;min-height:0;display:grid;gap:22px;align-content:center}.native-group{min-width:0}.native-group-title{font-size:calc(var(--native-size)*.76);line-height:1.25;font-weight:650;letter-spacing:.015em;color:#a9dfca;margin:0 0 12px}.native-points{list-style:none;padding:0;margin:0;display:grid;gap:.5em}.native-points li{position:relative;padding-left:.9em;font-size:var(--native-size);line-height:1.4;color:#dde8e3;margin:0;white-space:pre-line;overflow-wrap:anywhere}.native-points li:before{content:'';position:absolute;left:0;top:.63em;width:.22em;height:.22em;border-radius:50%;background:#77bca6}.native-points li:only-child{padding-left:0}.native-points li:only-child:before{display:none}
.native-figures{display:grid;grid-template-columns:repeat(auto-fit,minmax(0,1fr));gap:16px;grid-auto-rows:minmax(0,1fr);min-height:0;height:100%;min-width:0;align-items:stretch}.native-figure{display:flex;flex-direction:column;min-height:0;height:100%;max-height:100%;margin:0;gap:9px;min-width:0}.native-image{position:relative;display:flex;justify-content:center;align-items:center;min-width:0;min-height:0;max-height:100%;border:1px solid #3e5b60;background:#fff;padding:8px;border-radius:8px;cursor:zoom-in;overflow:hidden;width:100%;height:100%;flex:1 1 0}.native-enlarge{position:absolute;right:7px;top:7px;border-radius:4px;background:#102920e8;color:#d4f3e3;padding:2px 6px;font:16px/1.2 system-ui,sans-serif;pointer-events:none}.native-image:focus-visible{outline:3px solid #91edbc;outline-offset:4px}.native-figure img{display:block;max-width:100%;width:100%;height:100%;max-height:100%;min-height:0;object-fit:contain;background:white;border-radius:3px}.native-figure figcaption{font-size:clamp(12px,.95vw,17px);line-height:1.4;color:#a7bdb5;margin:0;flex:none}.native-takeaway{flex:none;border-left:3px solid #7acaab;padding:10px 18px;margin:0;font-size:clamp(17px,1.4vw,25px);line-height:1.4;color:#c4e9d9;background:#71bd9710;max-width:110ch}
.native-lecture[data-layout=split] .native-body{grid-template-columns:minmax(0,.95fr) minmax(0,1.2fr)}.native-lecture[data-layout=split][data-density=medium] .native-body,.native-lecture[data-layout=split][data-density=dense] .native-body{grid-template-columns:minmax(0,1.15fr) minmax(0,1fr)}.native-lecture[data-layout=split] .native-figures{grid-template-columns:1fr}.native-lecture[data-layout=split][data-figures='2'] .native-figures{grid-template-columns:1fr 1fr}.native-lecture[data-layout=gallery] .native-body{grid-template-rows:min-content minmax(0,1fr);align-items:stretch;gap:18px}.native-lecture[data-layout=gallery] .native-groups{display:flex;gap:26px}.native-lecture[data-layout=gallery] .native-group{flex:1}.native-lecture[data-layout=gallery] .native-points li{font-size:calc(var(--native-size)*.8)}.native-lecture[data-groups='0'] .native-body{grid-template-rows:minmax(0,1fr)}
.native-lecture[data-layout=text] .native-groups,.native-lecture[data-layout=comparison] .native-groups{grid-template-columns:repeat(auto-fit,minmax(280px,1fr));align-items:start;gap:36px}.native-lecture[data-layout=comparison] .native-group+.native-group{border-left:1px solid #436057;padding-left:30px}.native-lecture[data-layout=title]{justify-content:center;gap:30px}.native-lecture[data-layout=title] .native-title{font-size:clamp(45px,5.5vw,90px);max-width:22ch}.native-lecture[data-layout=title] .native-body{flex:0 0 auto;min-height:min-content}.native-lecture[data-layout=title] .native-points li{font-size:clamp(21px,2vw,32px);color:#a5bbb3}.native-lecture[data-density=medium]{--native-size:clamp(19px,1.68vw,29px)}.native-lecture[data-density=dense]{--native-size:clamp(17px,1.42vw,24px);gap:16px}.native-lecture[data-density=dense] .native-points{gap:.4em}.native-lecture[data-density=dense] .native-groups{gap:18px}.native-lecture[data-density=dense] .native-title{font-size:clamp(28px,2.8vw,46px)}
@media(max-width:720px){.native-lecture{--native-size:20px!important;height:auto;min-height:100%;gap:24px}.native-title{font-size:34px}.native-body,.native-lecture[data-layout=split] .native-body{display:flex;flex-direction:column;gap:24px;align-items:stretch}.native-groups,.native-lecture[data-layout=gallery] .native-groups{display:grid!important;grid-template-columns:1fr!important;gap:24px!important}.native-figures{height:auto;min-height:200px}.native-figure img{max-height:420px}.native-lecture[data-layout=comparison] .native-group+.native-group{border-left:0;border-top:1px solid #436057;padding:24px 0 0}.native-lecture[data-layout=title] .native-title{font-size:48px}}
`;
