import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { aggregateRequests, temporalView } from '../public/scripts/scads-demo.js';

const load = async (name) => JSON.parse(await readFile(new URL(`../public/data/scads/${name}.json`, import.meta.url), 'utf8'));
const requests = (await load('02-311-analytics')).rows;
const original = JSON.stringify(requests);

// FIX-013 is closed but has no duration. Preserve it in the closure count while
// excluding it from the mean, rather than treating its missing measurement as 0.
const all = aggregateRequests(requests);
assert.equal(all.selected.length, 32);
assert.equal(all.closed, 24);
assert.equal(all.timed, 23);
assert.equal(all.mean, 508 / 23);
const rodents = aggregateRequests(requests, { borough: 'BROOKLYN', complaint_type: 'Rodent' });
assert.deepEqual(rodents.selected.map((row) => row.unique_key), ['FIX-001', 'FIX-002', 'FIX-013', 'FIX-017', 'FIX-018', 'FIX-019', 'FIX-020']);
assert.equal(rodents.closed, 6);
assert.equal(rodents.timed, 5);
assert.equal(rodents.mean, 31.2);
const open = aggregateRequests(requests, { status: 'Open' });
assert.equal(open.selected.length, 8);
assert.equal(open.mean, null);
const absent = aggregateRequests(requests, { borough: 'No such borough' });
assert.equal(absent.selected.length, 0);
assert.equal(absent.mean, null);
assert.equal(JSON.stringify(requests), original, 'Filtering must not mutate the bundled records');

// Independently authored gold cases are copied verbatim from the project's
// temporal fixture; their expected IDs/modalities are not generated by this UI.
const temporal = await load('05-graphrag-discovery');
for (const state of temporal.verificationCases) {
  const result = temporalView(temporal, state.knowledge_cutoff, state.valid_time);
  assert.deepEqual(result.assertions.map((claim) => claim.assertion_id).sort(), [...state.assertion_ids].sort(), state.id);
  assert.deepEqual(Object.fromEntries(result.assertions.map((claim) => [claim.assertion_id, claim.modality])), state.modalities, state.id);
  assert.equal(Boolean(result.disputed), state.disputed_ids.length > 0, state.id);
}
assert.equal(temporalView(temporal, '2025-02-10T10:04:59Z', '2025-02-04T00:00:00Z').assertions[0].assertion_id, 'b-planned', 'Staged correction is not published knowledge');
assert.equal(temporalView(temporal, '2025-02-10T10:05:00Z', '2025-02-04T00:00:00Z').assertions[0].assertion_id, 'b-corrected', 'Publication makes the correction queryable');
assert.equal(temporalView(temporal, '2025-02-13T00:00:00Z', '2025-02-04T00:00:00Z', 'planned').assertions.length, 0, 'Claim-type filters do not promote plans');

const sensemaking = await load('01-sensemaking');
for (const finding of sensemaking.findings) for (const id of finding.evidence_ids) {
  assert.ok(sensemaking.evidence.some((item) => item.id === id && item.text), `Missing evidence: ${id}`);
}
assert.ok(sensemaking.findings[0].evidence_ids.includes('tbl-003'), 'Readiness includes the earlier ready claim');
const observations = (await load('03-semantic-discovery')).observations;
assert.equal(observations.length, 14);
assert.equal(new Set(observations.map((row) => row.doc_id)).size, 4);
assert.equal(observations.find((row) => row.model === 'M7' && row.attribute === 'output_power').value, 28000, '35 kVA must not become 35 kW');
assert.deepEqual(observations.find((row) => row.model === 'HR-28' && row.attribute === 'output_voltage').conditions, ['DC'], 'DC output must not receive an inferred AC frequency');
const graph = await load('04-org-knowledge-graphs');
assert.equal(graph.entities.filter((entity) => entity.name === 'Alex Morgan').length, 2, 'Same-name people retain separate identities');
assert.equal(graph.edges.filter((edge) => edge.kind === 'communication').length, 3, 'Deduplicate messages and exclude undated/malformed rows');
assert.ok(!graph.edges.some((edge) => edge.from === 'taylor' && edge.to === 'casey' && edge.kind === 'reporting'), 'Coordination must not imply a manager');
console.log('SCADS browser semantics pass: missing durations, conjunctive filters, 8 temporal gold cases, publication boundaries, source references, units, identities, and relationship layers.');
